# Generated by Django 2.2.4 on 2019-09-13 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokengenerator',
            options={},
        ),
        migrations.RemoveField(
            model_name='tokengenerator',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tokengenerator',
            name='key',
        ),
        migrations.RemoveField(
            model_name='tokengenerator',
            name='user',
        ),
        migrations.AddField(
            model_name='tokengenerator',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token'),
            preserve_default=False,
        ),
    ]
