# Generated by Django 2.2.4 on 2019-08-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('On Progress', 'On Progress'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
    ]
