# Generated by Django 2.2.4 on 2019-09-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenGenerator',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
            ],
            bases=('authtoken.token',),
        ),
    ]
